name: Create Accounts

# This workflow is triggered manually
on:
  workflow_dispatch:
    inputs:
      accounts_count:
        description: 'Number of accounts to create'
        required: true
        default: '1'
        type: number

jobs:
  create-accounts:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          echo "Using package.json from repository..."
          cat package.json
          echo "Checking for package-lock.json..."
          ls -la
          echo "Installing dependencies..."
          npm ci || npm install
      
      - name: Install Puppeteer dependencies
        run: |
          sudo apt-get update
          # Install modern Chrome dependencies (for Ubuntu 22.04)
          # Enable universe repository (for some dependencies)
          sudo add-apt-repository universe
          sudo apt-get update

          # Install dependencies in smaller groups for better error handling
          echo "Installing basic tools..."
          sudo apt-get install -y --no-install-recommends \
            wget \
            unzip \
            fontconfig \
            locales \
            ca-certificates \
            fonts-liberation
            
          echo "Installing libraries part 1..."
          sudo apt-get install -y --no-install-recommends \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libc6 \
            libcairo2 \
            libcups2 \
            libdbus-1-3 \
            libexpat1 \
            libfontconfig1
            
          echo "Installing libraries part 2..."
          sudo apt-get install -y --no-install-recommends \
            libgbm1 \
            libglib2.0-0 \
            libgtk-3-0 \
            libnspr4 \
            libnss3 \
            libpango-1.0-0 \
            libpangocairo-1.0-0
            
          echo "Installing libraries part 3..."
          sudo apt-get install -y --no-install-recommends \
            libstdc++6 \
            libx11-6 \
            libx11-xcb1 \
            libxcb1 \
            libxcomposite1 \
            libxcursor1 \
            libxdamage1 \
            libxext6 \
            libxfixes3 \
            libxi6 \
            libxrandr2 \
            libxrender1 \
            libxss1 \
            libxtst6 \
            lsb-release \
            xdg-utils
            
          # Try to install ALSA as an alternative to libasound2 (if needed)
          echo "Attempting to install audio libraries..."
          sudo apt-get install -y --no-install-recommends alsa-base alsa-utils || true
      
      - name: Debug environment
        run: |
          echo "Workspace contents:"
          ls -la
          echo "Node.js version:"
          node --version
          echo "Checking module paths:"
          node -e "console.log('Module paths:', module.paths)"
          echo "Checking utils.js file:"
          cat utils.js | head -10
          
      - name: Create accounts with verbose logging
        run: |
          echo "Ensuring utils.js is in the correct location:"
          cp utils.js ./utils.js 2>/dev/null || echo "utils.js already in place"
          echo "Running with increased debugging:"
          NODE_DEBUG=module node --trace-warnings create-accounts.js
      
      - name: Upload accounts file
        uses: actions/upload-artifact@v4
        with:
          name: created-accounts
          path: accounts.txt
          retention-days: 1
